### ISSUE TITLE
Got permission denied while trying to connect to the Docker daemon socket

### ISSUE THREAD

**Issue by cnpcshangbo** [Alexey-Kamenev/scripts_and_more#3]
Hi
I am using Ubuntu 14.04 and I got this error.
Does it mean I need to install something else?
Thanks,
Bo
```
bshang2@mechatronicslab-OptiPlex-990:~$ sudo xhost +local:`docker ps -aqf "name=erle-sim"`
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.30/containers/json?all=1&filters=%7B%22name%22%3A%7B%22erle-sim%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied
non-network local connections being added to access control list
```

**Comment by Alexey-Kamenev** [comment]
Hi,
Sorry for delay with response. As [Lander suggests](http://forum.erlerobotics.com/t/running-simulation-in-docker/2752/12) try adding user to docker group and verify that you can create new containers without `sudo`, something like that:
```
docker run --rm hello-world
```
Don't forget to log out/log in after adding yourself to the group.

**Comment by cnpcshangbo** [comment]
Thank you @Alexey-Kamenev I'll try that.

**Comment by cnpcshangbo** [comment]
@Alexey-Kamenev I can run the docker without `sudo` now.
